### ISSUE TITLE
Exception Message: Could not find a part of the path 'D:\Free VR\rookie_2.18_portable'.

### ISSUE THREAD

**Issue by Limer1492** [Chax1/VRPE-Installer#15] opened 2023-01-08 02:50 UTC
This popped up while trying to launch Rookie. It said to post the problem here so I did. Any help would be greatly appreciated.

**Comment by Chax1** [comment] 2023-01-08 02:55
Hey there, thanks for writing an issue post, quick explanation on how the logging system/launching system works.

When downloading Rookie the VRPE will log the path it was last downloaded into inside of a .txt file stored in C:/RSL/
When you press the launch button it looks for any exe called AndroidSideloader and will launch it,

Did you move the folder the VRPE did its download in at all?

**Comment by Limer1492** [comment] 2023-01-08 03:00
I think I figured it out. It was asking for the sideloader but it was asking for it by a different name than what it was showing up as in the folder. Once I chose the path to be the sideloader file with a different name than what it was asking for it ended up working. Thanks for replying so quickly!

**Comment by Chax1** [comment] 2023-01-08 03:01
Do you mean the folder name? Since you wrote it couldn't find the path and not file.

**Comment by Chax1** [comment] 2023-01-08 03:38
As the issue has been fixed for you and there hasn't been a response for 30+ min I will close this issue and add a fix inside of the VRPE that will prevent the launch button appearing when the folder its logged does not exist anymore.

**Comment by Limer1492** [comment] 2023-01-08 03:44
No the folder name was correct but the specific file it was asking for was not there. I saw another file that said sideloader on it so I tried that file and once I chose that file it started working. Below is the file that I chose to use instead fo the one it asked for.
![Untitled](https://user-images.githubusercontent.com/100656404/211179519-fe3aacf0-6e68-47cc-9581-e98b8bbad1bf.png)

**Comment by Chax1** [comment] 2023-01-08 03:47
Wait the VRPE asked for a file? 

Could you show me?

**Comment by Chax1** [comment] 2023-01-08 03:49
![image](https://user-images.githubusercontent.com/69131569/211179624-5c027f6e-536a-40c4-bcc9-58bebc178f50.png)

This would confuse me, as this is currently how the launching system works, like I said it will look for any exe with AndroidSideloader...

**Comment by Limer1492** [comment] 2023-01-08 03:52
I feel like I may just be being dumb and not understanding something so sorry if I'm just being stupid. This is the thing it asked for. Again sorry if I'm just being stupid.
![Untitleed](https://user-images.githubusercontent.com/100656404/211179676-c46c6a33-b1d7-466c-90ec-f06edc888d7f.png)

**Comment by Chax1** [comment] 2023-01-08 03:53
> I feel like I may just be being dumb and not understanding something so sorry if I'm just being stupid. This is the thing it asked for. Again sorry if I'm just being stupid. ![Untitleed](https://user-images.githubusercontent.com/100656404/211179676-c46c6a33-b1d7-466c-90ec-f06edc888d7f.png)

Hey dont worry, no need to call yourself stupid lol, thats why you made an issue post, right, I believe the folder name would be incorrect then as it cannot find that path, could you screenshot the folder D:\Free VR\ for me (Not the rookie folder but the one outside of it)

**Comment by Limer1492** [comment] 2023-01-08 03:55
![Untitleeed](https://user-images.githubusercontent.com/100656404/211179766-9debeb88-7a91-45a9-a4d0-be0c8657cc8e.png)

**Comment by Chax1** [comment] 2023-01-08 03:56
Ah, I figured out what the issue is ^^

**Comment by Chax1** [comment] 2023-01-08 03:56
This is due to me not packing the damn new release into a folder, its on our end, the VRPE works fine, just a flaw in how I packaged stuff, have a nice day, will be fixed ASAP.

**Comment by Limer1492** [comment] 2023-01-08 03:57
Thanks so much for your help and replying so quickly!

**Closed** 2023-01-08 03:57 UTC
Labels: question
